<div id="footer">
	<div class="wrapper">
		<div class="side-padding">
			yadda. is &copy; <?php echo date('Y') ?> NG Development (Pty) Ltd. |
			<a href="<?php echo $this->url(array(), 'contact') ?>" title="Contact yadda.">contact us</a> or
			<a href="http://twitter.com/yaddacoza" title="@yaddacoza">follow us on Twitter</a>.
			<a href="http://<?php echo $this->config->domain->m ?>/?from=www" title="Mobi site">mobi site</a>.
		</div>
	</div>
</div>