<div id="header">
	<div class="wrapper">
		<div class="logo">
			<a href="/" title="Home">yadda.</a>
		</div>
		<?php echo $this->partial('_sharing.phtml') ?>
		<?php //echo $this->adsense('header') ?>
        <div class="adsense">
            <a href="http://ubuntudeal.co.za/competition/summer/enter/" title="WIN! UbuntuDeal">
                <img src="/img/ads/ubuntudeal.jpg" alt="WIN! UbuntuDeal" />
            </a>
        </div>
	</div>
</div>