<?php echo $this->doctype() ?>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">

<head>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headMeta() ?>
	<?php echo $this->minHeadLink() ?>
	<?php echo $this->minHeadScript() ?>
	<?php if (APPLICATION_ENVIRONMENT == 'production'): ?>
	<script type="text/javascript">
	// <![CDATA[
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-24121068-1']);
	_gaq.push(['_trackPageview']);
	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
	// ]]>
	</script>
	<?php endif; ?>
	<?php if (isset($this->deal)): ?>
	<meta name="og:title" content="[via <?php echo $this->escape($this->deal['site']['name']) ?>] <?php echo $this->escape($this->deal['title']) ?>" />
	<meta name="og:type" content="article" />
	<meta name="og:url" content="http://yadda.co.za/deal/<?php echo $this->deal['id'] ?>" />
	<?php if (isset($this->deal['thumbs'])): ?>
	<meta name="og:image" content="<?php echo $this->deal['thumbs']['listing'] ?>" />
	<?php endif; ?>
	<?php endif; ?>
</head>

<body>
	<div id="wrapper">
		<?php echo $this->layout()->content ?>
	</div>
	<?php if (sizeof($this->flashMessages) > 0): ?>
	<div id="flash">
		<p><?php echo $this->escape($this->flashMessages[0]) ?></p>
	</div>
	<?php endif; ?>
	<div id="fb-root"></div>
	<script src="http://connect.facebook.net/en_US/all.js" type="text/javascript"></script>
	<script type="text/javascript">
	// <![CDATA[
	FB.init({
		appId  : '<?php echo $this->config->facebook->appId ?>',
		status : true, // check login status
		cookie : true, // enable cookies to allow the server to access the session
		xfbml  : true  // parse XFBML
	});
	// ]]>
	</script>
</body>

</html>